export const fontOptions = [
  {
    label: "Serif Fonts",
    options: [
      { name: "Roboto Slab", value: "Roboto Slab, serif", style: "Roboto Slab, serif" },
      {
        name: "Playfair Display",
        value: "Playfair Display, serif",
        style: "Playfair Display, serif",
      },
      // { name: "Merriweather", value: "'Merriweather', serif", style: "'Merriweather', serif" },
      // { name: "Lora", value: "'Lora', serif", style: "'Lora', serif" },
      // { name: "EB Garamond", value: "'EB Garamond', serif", style: "'EB Garamond', serif" },
      // { name: "PT Serif", value: "'PT Serif', serif", style: "'PT Serif', serif" },
      { name: "Noto Serif", value: "'Noto Serif', serif", style: "'Noto Serif', serif" },
      { name: "Crimson Text", value: "'Crimson Text', serif", style: "'Crimson Text', serif" },
      { name: "Cormorant", value: "'Cormorant', serif", style: "'Cormorant', serif" },
      { name: "Abril Fatface", value: "Abril Fatface, serif", style: "Abril Fatface, serif" },
      { name: "Chicle", value: "Chicle, serif", style: "Chicle, serif" },
      { name: "Shrikhand", value: "Shrikhand, serif", style: "Shrikhand, serif" },
      {
        name: "Cinzel Decorative",
        value: "Cinzel Decorative, serif",
        style: "Cinzel Decorative, serif",
      },
      { name: "Rye", value: "Rye, serif", style: "Rye, serif" },
      { name: "Arvo", value: "Arvo, serif", style: "Arvo, serif" },
      { name: "Crete Round", value: "Crete Round, serif", style: "Crete Round, serif" },
      { name: "Josefin Slab", value: "Josefin Slab, serif", style: "Josefin Slab, serif" },
      { name: "Alfa Slab One", value: "Alfa Slab One, serif", style: "Alfa Slab One, serif" },
      { name: "Slabo 27px", value: "Slabo 27px, serif", style: "Slabo 27px, serif" },
      { name: "Ultra", value: "Ultra, serif", style: "Ultra, serif" },
      { name: "Vast Shadow", value: "Vast Shadow, serif", style: "Vast Shadow, serif" },
      { name: "Caudex", value: "Caudex, serif", style: "Caudex, serif" },
      { name: "Patua One", value: "Patua One, serif", style: "Patua One, serif" },
      { name: "Bree Serif", value: "Bree Serif, serif", style: "Bree Serif, serif" },
    ],
  },
  {
    label: "Sans-serif Fonts",
    options: [
      { name: "Roboto", value: "Roboto, sans-serif", style: "Roboto, sans-serif" },
      { name: "Open Sans", value: "Open Sans, sans-serif", style: "Open Sans, sans-serif" },
      { name: "Lato", value: "Lato, sans-serif", style: "Lato, sans-serif" },
      { name: "Montserrat", value: "Montserrat, sans-serif", style: "Montserrat, sans-serif" },
      { name: "Poppins", value: "Poppins, sans-serif", style: "Poppins, sans-serif" },
      { name: "Inter", value: "Inter, sans-serif", style: "Inter, sans-serif" },
      { name: "Raleway", value: "Raleway, sans-serif", style: "Raleway, sans-serif" },
      { name: "Nunito", value: "Nunito, sans-serif", style: "Nunito, sans-serif" },
      { name: "Mulish", value: "Mulish, sans-serif", style: "Mulish, sans-serif" },
      { name: "Bebas Neue", value: "Bebas Neue, sans-serif", style: "Bebas Neue, sans-serif" },
      { name: "Teko", value: "Teko, sans-serif", style: "Teko, sans-serif" },
      { name: "Lilita One", value: "Lilita One, sans-serif", style: "Lilita One, sans-serif" },
      {
        name: "Archivo Black",
        value: "Archivo Black, sans-serif",
        style: "Archivo Black, sans-serif",
      },
      { name: "Passion One", value: "Passion One, sans-serif", style: "Passion One, sans-serif" },
      {
        name: "Racing Sans One",
        value: "Racing Sans One, sans-serif",
        style: "Racing Sans One, sans-serif",
      },
      { name: "Titan One", value: "Titan One, sans-serif", style: "Titan One, sans-serif" },
      { name: "Federo", value: "Federo, sans-serif", style: "Federo, sans-serif" },
      { name: "Ubuntu", value: "Ubuntu, sans-serif", style: "Ubuntu, sans-serif" },
      { name: "Quicksand", value: "Quicksand, sans-serif", style: "Quicksand, sans-serif" },
      { name: "Josefin Sans", value: "Josefin Sans, sans-serif", style: "Josefin Sans, sans-serif" },
    ],
  },
  {
    label: "Display Fonts",
    options: [
      { name: "Bungee", value: "Bungee, display", style: "Bungee, display" },
      { name: "Anton", value: "Anton, display", style: "Anton, display" },
      { name: "Oswald", value: "Oswald, display", style: "Oswald, display" },
      { name: "Righteous", value: "Righteous, display", style: "Righteous, display" },
      { name: "Lobster", value: "Lobster, display", style: "Lobster, display" },
      { name: "Pacifico", value: "Pacifico, display", style: "Pacifico, display" },
      { name: "Fredoka", value: "Fredoka, display", style: "Fredoka, display" },
      { name: "Monoton", value: "Monoton, display", style: "Monoton, display" },
      { name: "Fredericka the Great", value: "Fredericka the Great, display", style: "Fredericka the Great, display" },
      { name: "Black Ops One", value: "Black Ops One, display", style: "Black Ops One, display" },
      { name: "Ruslan Display", value: "Ruslan Display, display", style: "Ruslan Display, display" },
      { name: "Orbitron", value: "Orbitron, display", style: "Orbitron, display" },
      { name: "Bangers", value: "Bangers, display", style: "Bangers, display" },
      { name: "Cinzel Decorative", value: "Cinzel Decorative, display", style: "Cinzel Decorative, display" },
      { name: "Chewy", value: "Chewy, display", style: "Chewy, display" },
      { name: "Creepster", value: "Creepster, display", style: "Creepster, display" },
      { name: "Faster One", value: "Faster One, display", style: "Faster One, display" },
      { name: "Zilla Slab Highlight", value: "Zilla Slab Highlight, display", style: "Zilla Slab Highlight, display" },
      { name: "Unica One", value: "Unica One, display", style: "Unica One, display" },
      { name: "Sonsie One", value: "Sonsie One, display", style: "Sonsie One, display" },
    ],
  },
  // {
  //   label: "Handwriting Fonts",
  //   options: [
  //     { name: "Caveat", value: "Caveat, handwriting", style: "Caveat, handwriting" },
  //     {
  //       name: "Dancing Script",
  //       value: "Dancing Script, handwriting",
  //       style: "Dancing Script, handwriting",
  //     },
  //     { name: "Amatic SC", value: "Amatic SC, handwriting", style: "Amatic SC, handwriting" },
  //     {
  //       name: "Indie Flower",
  //       value: "Indie Flower, handwriting",
  //       style: "Indie Flower, handwriting",
  //     },
  //     {
  //       name: "Patrick Hand",
  //       value: "Patrick Hand, handwriting",
  //       style: "Patrick Hand, handwriting",
  //     },
  //     { name: "Sacramento", value: "Sacramento, handwriting", style: "Sacramento, handwriting" },
  //     {
  //       name: "Shadows Into Light",
  //       value: "Shadows Into Light, handwriting",
  //       style: "Shadows Into Light, handwriting",
  //     },
  //     { name: "Satisfy", value: "Satisfy, handwriting", style: "Satisfy, handwriting" },
  //     { name: "Alex Brush", value: "Alex Brush, handwriting", style: "Alex Brush, handwriting" },
  //   ],
  // },
  {
    label: "Monospace Fonts",
    options: [
      { name: "Fira Code", value: "Fira Code, monospace", style: "Fira Code, monospace" },
      {
        name: "JetBrains Mono",
        value: "JetBrains Mono, monospace",
        style: "JetBrains Mono, monospace",
      },
      {
        name: "Source Code Pro",
        value: "Source Code Pro, monospace",
        style: "Source Code Pro, monospace",
      },
      { name: "Inconsolata", value: "Inconsolata, monospace", style: "Inconsolata, monospace" },
      { name: "Roboto Mono", value: "Roboto Mono, monospace", style: "Roboto Mono, monospace" },
      { name: "Space Mono", value: "Space Mono, monospace", style: "Space Mono, monospace" },
      {
        name: "IBM Plex Mono",
        value: "IBM Plex Mono, monospace",
        style: "IBM Plex Mono, monospace",
      },
      { name: "Cousine", value: "Cousine, monospace", style: "Cousine, monospace" },
      { name: "PT Mono", value: "PT Mono, monospace", style: "PT Mono, monospace" },
      { name: "Ubuntu Mono", value: "Ubuntu Mono, monospace", style: "Ubuntu Mono, monospace" },
      { name: "DM Mono", value: "DM Mono, monospace", style: "DM Mono, monospace" },
      { name: "Lekton", value: "Lekton, monospace", style: "Lekton, monospace" },
      { name: "Syne Mono", value: "Syne Mono, monospace", style: "Syne Mono, monospace" },
      {
        name: "Courier Prime",
        value: "'Courier Prime', monospace",
        style: "'Courier Prime', monospace",
      },
      { name: "Cutive Mono", value: "'Cutive Mono', monospace", style: "'Cutive Mono', monospace" },
      { name: "Share Tech Mono", value: "'Share Tech Mono', monospace", style: "'Share Tech Mono', monospace" },
      { name: "Oxygen Mono", value: "'Oxygen Mono', monospace", style: "'Oxygen Mono', monospace" },
      { name: "VT323", value: "'VT323', monospace", style: "'VT323', monospace" },
      {
        name: "Overpass Mono",
        value: "'Overpass Mono', monospace",
        style: "'Overpass Mono', monospace",
      },
      {
        name: "Anonymous Pro",
        value: "'Anonymous Pro', monospace",
        style: "'Anonymous Pro', monospace",
      },
    ],
  },
  {
    label: "Cursive Fonts",
    options: [
      { name: "Yellowtail", value: "Yellowtail, cursive", style: "Yellowtail, cursive" },
      {
        name: "Gloria Hallelujah",
        value: "Gloria Hallelujah, cursive",
        style: "Gloria Hallelujah, cursive",
      },
      {
        name: "Cedarville Cursive",
        value: "Cedarville Cursive, cursive",
        style: "Cedarville Cursive, cursive",
      },
      { name: "Style Script", value: "Style Script, cursive", style: "Style Script, cursive" },
      { name: "Cookie", value: '"Cookie", cursive', style: '"Cookie", cursive' },
      { name: "Coming Soon", value: '"Coming Soon", cursive', style: '"Coming Soon", cursive' },
      { name: "Great Vibes", value: '"Great Vibes", cursive', style: '"Great Vibes", cursive' },
      { name: "Luckiest Guy", value: '"Luckiest Guy", cursive', style: '"Luckiest Guy", cursive' },
      { name: "Rock Salt", value: '"Rock Salt", cursive', style: '"Rock Salt", cursive' },
      { name: "Zeyada", value: '"Zeyada", cursive', style: '"Zeyada", cursive' },
      { name: "La Belle Aurore", value: '"La Belle Aurore", cursive', style: '"La Belle Aurore", cursive' },
      { name: "Give You Glory", value: '"Give You Glory", cursive', style: '"Give You Glory", cursive' },
      { name: "Reenie Beanie", value: '"Reenie Beanie", cursive', style: '"Reenie Beanie", cursive' },
      { name: "Kristi", value: '"Kristi", cursive', style: '"Kristi", cursive' },
      { name: "Just Another Hand", value: '"Just Another Hand", cursive', style: '"Just Another Hand", cursive' },
      { name: "Homemade Apple", value: '"Homemade Apple", cursive', style: '"Homemade Apple", cursive' },
      { name: "Handlee", value: '"Handlee", cursive', style: '"Handlee", cursive' },
      { name: "Architects Daughter", value: '"Architects Daughter", cursive', style: '"Architects Daughter", cursive' },
      { name: "Allura", value: '"Allura", cursive', style: '"Allura", cursive' },
      { name: "Covered By Your Grace", value: '"Covered By Your Grace", cursive', style: '"Covered By Your Grace", cursive' },
    ],
  },
];
